version: "3.1"
services:

  postgres:
    restart: always
    image: postgres:latest
    environment:
      - POSTGRES_DB=${POSTGRES_DB}
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
    ports:
      - "5432:5432"
    volumes:
      - ./pgdata:/var/lib/postgresql/data/

  redis:
    image: redis:alpine
    ports:
      - "6379:6379"
    volumes:
     - ./redisdata:/data

  ellipticoin-server:
    build: 
      context: ./ellipticoin-server
      args:
        - PRIVATE_KEY=${PRIVATE_KEY}
    ports:
      - "80:80"
      - "3030:3030"
    restart: always
    tty: true
    stdin_open: true
    environment:
      - RUST_BACKTRACE=${RUST_BACKTRACE}
      - HOST=${HOST}
      - ENABLE_MINER=true
      - BURN_PER_BLOCK=100
      - PRIVATE_KEY=${PRIVATE_KEY}
      - DATABASE_URL=postgresql://${POSTGRES_USER}:${POSTGRES_PASSWORD}@postgres:5432/${POSTGRES_DB}
    depends_on:
      - postgres
      - redis
    links:
      - "postgres"
      - "redis"
    # volumes:
    #   - ./shared/:/shared/
    command: bash -c "wait-for-it -s postgres:5432 -s redis:6379 --  /root/ellipticoind/target/release/ellipticoind --database-url postgresql://${POSTGRES_USER}:${POSTGRES_PASSWORD}@postgres:5432/${POSTGRES_DB} --redis-url redis://redis:6379"    

# volumes:
#   pgdata:
#   shared:
